name: Redeploy Vercel App

on:
  schedule:
    # Runs every 2 hours (0 */2 * * *)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Trigger Vercel deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_uEvbZmTVbZyyGqvustIMnCSsAw9P/5KJpe02fVl"
        # Alternative: Use Vercel CLI
        # env:
        #   VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        # run: |
        #   npx vercel --prod --token $VERCEL_TOKEN